apiVersion: v1
kind: Secret
metadata:
  name: smtp-secret
  namespace: email-marketing
type: Opaque
stringData:
  SMTP_USER: "AKIA2BCTWUOB22GRAPQI"
  SMTP_PASS: "BH7pNq/emsTJl5P+g9MPgWtmhzO5n/kBkKOmUYZNXvGm"
