---
apiVersion: v1
kind: Service
metadata:
  name: k3s-portal-backend
  namespace: k3s-portal
  labels:
    app.kubernetes.io/name: k3s-portal
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/name: k3s-portal
    app.kubernetes.io/component: backend
  ports:
    - port: 3010
      targetPort: 3010
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: k3s-portal-frontend
  namespace: k3s-portal
  labels:
    app.kubernetes.io/name: k3s-portal
    app.kubernetes.io/component: frontend
spec:
  selector:
    app.kubernetes.io/name: k3s-portal
    app.kubernetes.io/component: frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
